/**
 * Vercel build script — runs once at deploy time.
 * Reads Supabase env vars injected by the Vercel <> Supabase integration
 * and writes them into a static JS module that the browser can import.
 *
 * Env vars set automatically by the Vercel Supabase integration:
 *   SUPABASE_URL, SUPABASE_ANON_KEY
 */

const fs   = require("fs");
const path = require("path");

const url = process.env.SUPABASE_URL || "";
const key = process.env.SUPABASE_ANON_KEY || "";

if (!url || !key) {
  console.warn(
    "[build] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is not set. " +
    "The app will not be able to connect to Supabase."
  );
}

const content = `// ⚠️  Auto-generated by build.js — do not edit or commit.
// Regenerated on every Vercel deploy from environment variables.
export const SUPABASE_URL      = "${url}";
export const SUPABASE_ANON_KEY = "${key}";
`;

const outPath = path.join(__dirname, "web-app/assets/js/env.js");
fs.writeFileSync(outPath, content, "utf8");
console.log(`[build] env.js written (url=${url ? "✓" : "missing"}, key=${key ? "✓" : "missing"})`);
